#!/usr/bin/python
from infiniti.rpc import *
import argparse
import sys
from utils.crypto import valid_address
from infiniti.params import *

if __name__ == "__main__":
	coins = []
	for k,v in VERWIF.iteritems():
		coins.append(k)

	parser = argparse.ArgumentParser()
	parser.add_argument("command", help="Command to execute", choices=[ "listwallets","walletbalance","getnewaddress",
																		"listaddresses","addressbalance", "createwallet",
																		"verifymessage","signmessage","dumpaddress",
																		"sync","listunspent","reindex","getinfo","importwallet",
																		"exportwallet","createvault","openvault"
																		])
	parser.add_argument("-w","--wallet", help="The wallet to use")
	parser.add_argument("-a","--address", help="An address to use")
	parser.add_argument("-b","--blockchain", help="The blockchain to use",type=str, choices=coins)
	parser.add_argument("-p","--passphrase", help="The wallet passphrase")
	parser.add_argument("-m","--message", help="The message to verify")
	parser.add_argument("-s","--signature", help="The signature of the message to verify")
	parser.add_argument("-t","--type", help="The address type to create, default = 0",type=int, choices=[0,1,2,3])
	parser.add_argument("-f","--filename", help="A filename",type=str)
	parser.add_argument("-j","--json", help="A JSON formatted string",type=str)
	parser.add_argument("-n","--numaddr", help= "Number of vault addresses to create (default: 5)", type=int)
	parser.add_argument("-x","--numshares", help= "Number of parts into which to split the vault secret (default: 15)", type=str)
	parser.add_argument("-y","--numsharesrequired", help= "Minimum number of pieces which may be used to reconstruct a vault (default: 5)", type=str)
	parser.add_argument("-z","--password_array", help= "An array of passwords, number of elements must equal the number of parts requested, parts encrypted in array order", type=str)
	parser.add_argument("-0","--verwif_array", help= "An array of [version_byte, wif_byte] for deposit address encoding.", type=str)
	parser.add_argument("-1","--shares_array", help= "An array of shares needed to open a vault.", type=str)

	args = parser.parse_args()

	if args.command == "createvault":
		print createvault(args.numshares,args.numsharesrequired,args.numaddr,args.verwif_array,args.password_array)

	if args.command == "openvault":
		if args.passphrase is None:
			print "ERROR: No passphrase provided!"
		elif args.numaddr is None:
			print "ERROR: Number of addresses must be greater than zero!"
		elif args.password_array is None:
			print openvault(args.numaddr,args.shares_array,args.passphrase)
		else:
			print openvault(args.numaddr,args.shares_array,args.passphrase,args.password_array)

	if args.command == "createwallet":
		if args.passphrase is None:
			print "ERROR: No passphrase provided!"
		else:
			print createwallet(args.passphrase)
	elif args.command == "exportwallet":
		if args.wallet is None:
			print "ERROR: No wallet provided!"
		else:
			print exportwallet(args.wallet)

	elif args.command == "importwallet":
		if args.filename is None:
			print "ERROR: No filename or JSON provided!"
		else:
			print importwallet(args.filename)

	elif args.command == "listwallets":
		print listwallets()

	elif args.command == "walletbalance":      
		if args.passphrase is None:
			print "ERROR: No passphrase specified!"
		elif args.wallet is None:
				print "ERROR: No wallet specified!"
		elif not os.path.isdir(os.path.join(WALLET_PATH, args.wallet)):
			print "ERROR: Wallet does not exist!"
		else:
			print walletbalance(args.wallet,args.passphrase)

	elif args.command == "getnewaddress":      
		if args.passphrase is None:
			print "ERROR: No passphrase specified!"
		elif args.wallet is None:
				print "ERROR: No wallet specified!"
		elif not os.path.isdir(os.path.join(WALLET_PATH, args.wallet)):
				print "ERROR: Wallet does not exist!"
		else:
			print newaddress(args.wallet,args.passphrase,args.type)

	elif args.command == "listaddresses":      
		if args.wallet is None:
			print "ERROR: No wallet specified!"
		elif not os.path.isdir(os.path.join(WALLET_PATH, args.wallet)):
				print "ERROR: Wallet does not exist!"
		else:
			print listaddresses(args.wallet)

	elif args.command == "sync":      
		sync()

	elif args.command == "reindex":      
		if args.passphrase is None:
			print "ERROR: No passphrase specified!"
		elif args.wallet is None:
				print "ERROR: No wallet specified!"
		elif not os.path.isdir(os.path.join(WALLET_PATH, args.wallet)):
			print "ERROR: Wallet does not exist!"
		else:
			sync(args.wallet,args.passphrase,True)

	elif args.command == "dumpaddress":      
		if args.address is None:
			print "ERROR: No address specified!"
		elif not valid_address(args.address):
			print "ERROR: Address provided is not a valid address"
		elif args.passphrase is None:
			print "ERROR: No passphrase specified!"
		elif args.wallet is None:
			print "ERROR: No wallet specified!"
		elif not os.path.isdir(os.path.join(WALLET_PATH, args.wallet)):
			print "ERROR: Wallet does not exist!"
		elif args.blockchain is None:
			print "ERROR: Blockchain not specified!"
		else:
			print dumpaddress(args.wallet,args.passphrase,args.address,args.blockchain)

	elif args.command == "signmessage":
		if args.message is None:
			print "ERROR: Message cannot be blank!"
		elif args.address is None:
			print "ERROR: No address specified!"
		elif not valid_address(args.address):
			print "ERROR: Address provided is not a Tao or Infiniti address"
		elif args.passphrase is None:
			print "ERROR: No passphrase specified!"
		elif args.wallet is None:
			print "ERROR: No wallet specified!"
		elif not os.path.isdir(os.path.join(WALLET_PATH, args.wallet)):
			print "ERROR: Wallet does not exist!"
		else:
			print signmessage(args.wallet,args.passphrase,args.address,args.message)

	elif args.command == "verifymessage":
		if args.message is None:
			print "ERROR: Message cannot be blank!"
		elif args.address is None:
			print "ERROR: No address specified!"
		elif not valid_address(args.address):
			print "ERROR: Address provided is not a Tao or Infiniti address"
		elif args.signature is None:
			print "ERROR: No signature specified!"
		else:
			print verifymessage(args.address,args.message,args.signature)

	elif args.command == "listunspent":      
		if args.wallet is None:
			print "ERROR: No wallet specified!"
		elif not os.path.isdir(os.path.join(WALLET_PATH, args.wallet)):
			print "ERROR: Wallet does not exist!"
		else:
			print listunspent(args.wallet)

	elif args.command == "addressbalance":      
		print addressbalance(args.address)

	elif args.command == "getinfo":      
		print getinfo()
