# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ip_deck.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ip_deck.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\rip_deck.proto\"\xde\x01\n\tDeckSpawn\x12\x0f\n\x07version\x18\x01 \x01(\r\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0c\n\x04uuid\x18\x03 \x01(\x0c\x12\x1a\n\x12number_of_decimals\x18\x04 \x01(\r\x12\x12\n\nissue_mode\x18\x05 \x01(\r\x12\x1b\n\x13\x61sset_specific_data\x18\x06 \x01(\x0c\x12\x0b\n\x03\x66\x65\x65\x18\x07 \x01(\r\"J\n\x04MODE\x12\x08\n\x04NONE\x10\x00\x12\n\n\x06\x43USTOM\x10\x01\x12\x08\n\x04ONCE\x10\x02\x12\t\n\x05MULTI\x10\x04\x12\x08\n\x04MONO\x10\x08\x12\r\n\tSINGLETON\x10\x18\x62\x06proto3')
)



_DECKSPAWN_MODE = _descriptor.EnumDescriptor(
  name='MODE',
  full_name='DeckSpawn.MODE',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NONE', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CUSTOM', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ONCE', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MULTI', index=3, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MONO', index=4, number=8,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SINGLETON', index=5, number=24,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=166,
  serialized_end=240,
)
_sym_db.RegisterEnumDescriptor(_DECKSPAWN_MODE)


_DECKSPAWN = _descriptor.Descriptor(
  name='DeckSpawn',
  full_name='DeckSpawn',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='DeckSpawn.version', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='DeckSpawn.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='uuid', full_name='DeckSpawn.uuid', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='number_of_decimals', full_name='DeckSpawn.number_of_decimals', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='issue_mode', full_name='DeckSpawn.issue_mode', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='asset_specific_data', full_name='DeckSpawn.asset_specific_data', index=5,
      number=6, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fee', full_name='DeckSpawn.fee', index=6,
      number=7, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _DECKSPAWN_MODE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=240,
)

_DECKSPAWN_MODE.containing_type = _DECKSPAWN
DESCRIPTOR.message_types_by_name['DeckSpawn'] = _DECKSPAWN
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DeckSpawn = _reflection.GeneratedProtocolMessageType('DeckSpawn', (_message.Message,), dict(
  DESCRIPTOR = _DECKSPAWN,
  __module__ = 'ip_deck_pb2'
  # @@protoc_insertion_point(class_scope:DeckSpawn)
  ))
_sym_db.RegisterMessage(DeckSpawn)


# @@protoc_insertion_point(module_scope)
