# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ip_metaproof.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ip_metaproof.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x12ip_metaproof.proto\"\xc3\x02\n\tMetaproof\x12\x0f\n\x07version\x18\x01 \x01(\r\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0c\n\x04uuid\x18\x03 \x01(\x0c\x12\x19\n\x11target_asset_uuid\x18\x04 \x01(\t\x12\x12\n\nproof_type\x18\x05 \x01(\r\x12\x13\n\x0b\x62urn_target\x18\x06 \x01(\t\x12\x0e\n\x06\x61mount\x18\x07 \x01(\r\x12\x13\n\x0bstart_block\x18\x08 \x01(\r\x12\x11\n\tend_block\x18\t \x01(\r\x12\x14\n\x0cproof_target\x18\n \x03(\x0c\x12\x1b\n\x13proof_specific_data\x18\x0b \x01(\x0c\x12\x0b\n\x03\x66\x65\x65\x18\x0c \x01(\r\"M\n\x04MODE\x12\x08\n\x04NONE\x10\x00\x12\n\n\x06\x43USTOM\x10\x01\x12\x08\n\x04\x42URN\x10\x02\x12\n\n\x06\x41MOUNT\x10\x04\x12\x0e\n\nTIMEPERIOD\x10\x08\x12\t\n\x05PROOF\x10\x10\x62\x06proto3')
)



_METAPROOF_MODE = _descriptor.EnumDescriptor(
  name='MODE',
  full_name='Metaproof.MODE',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NONE', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CUSTOM', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BURN', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='AMOUNT', index=3, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TIMEPERIOD', index=4, number=8,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PROOF', index=5, number=16,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=269,
  serialized_end=346,
)
_sym_db.RegisterEnumDescriptor(_METAPROOF_MODE)


_METAPROOF = _descriptor.Descriptor(
  name='Metaproof',
  full_name='Metaproof',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='Metaproof.version', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='Metaproof.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='uuid', full_name='Metaproof.uuid', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='target_asset_uuid', full_name='Metaproof.target_asset_uuid', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='proof_type', full_name='Metaproof.proof_type', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='burn_target', full_name='Metaproof.burn_target', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='amount', full_name='Metaproof.amount', index=6,
      number=7, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='start_block', full_name='Metaproof.start_block', index=7,
      number=8, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='end_block', full_name='Metaproof.end_block', index=8,
      number=9, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='proof_target', full_name='Metaproof.proof_target', index=9,
      number=10, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='proof_specific_data', full_name='Metaproof.proof_specific_data', index=10,
      number=11, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fee', full_name='Metaproof.fee', index=11,
      number=12, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _METAPROOF_MODE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=346,
)

_METAPROOF_MODE.containing_type = _METAPROOF
DESCRIPTOR.message_types_by_name['Metaproof'] = _METAPROOF
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Metaproof = _reflection.GeneratedProtocolMessageType('Metaproof', (_message.Message,), dict(
  DESCRIPTOR = _METAPROOF,
  __module__ = 'ip_metaproof_pb2'
  # @@protoc_insertion_point(class_scope:Metaproof)
  ))
_sym_db.RegisterMessage(Metaproof)


# @@protoc_insertion_point(module_scope)
