# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ip_card.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ip_card.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\rip_card.proto\"v\n\x0c\x43\x61rdTransfer\x12\x0f\n\x07version\x18\x01 \x01(\r\x12\x0e\n\x06\x61mount\x18\x02 \x03(\x04\x12\x0c\n\x04uuid\x18\x03 \x01(\x0c\x12\x1a\n\x12number_of_decimals\x18\x04 \x01(\r\x12\x1b\n\x13\x61sset_specific_data\x18\x05 \x01(\x0c\x62\x06proto3')
)




_CARDTRANSFER = _descriptor.Descriptor(
  name='CardTransfer',
  full_name='CardTransfer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='CardTransfer.version', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='amount', full_name='CardTransfer.amount', index=1,
      number=2, type=4, cpp_type=4, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='uuid', full_name='CardTransfer.uuid', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='number_of_decimals', full_name='CardTransfer.number_of_decimals', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='asset_specific_data', full_name='CardTransfer.asset_specific_data', index=4,
      number=5, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=135,
)

DESCRIPTOR.message_types_by_name['CardTransfer'] = _CARDTRANSFER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CardTransfer = _reflection.GeneratedProtocolMessageType('CardTransfer', (_message.Message,), dict(
  DESCRIPTOR = _CARDTRANSFER,
  __module__ = 'ip_card_pb2'
  # @@protoc_insertion_point(class_scope:CardTransfer)
  ))
_sym_db.RegisterMessage(CardTransfer)


# @@protoc_insertion_point(module_scope)
